<?php

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('settings')->delete();
        
        \DB::table('settings')->insert(array (
            0 => 
            array (
                'id' => '1',
                'key' => 'app_name',
                'name' => 'App Name',
                'value' => 'LaraClassified',
                'description' => 'Website name',
                'field' => '',
                'parent_id' => '0',
                'lft' => '2',
                'rgt' => '13',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            1 => 
            array (
                'id' => '2',
                'key' => 'app_logo',
                'name' => 'Logo',
                'value' => '',
                'description' => 'Website Logo',
                'field' => '{"name":"value","label":"Value","type":"browse"}',
                'parent_id' => '1',
                'lft' => '3',
                'rgt' => '4',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:27:49',
            ),
            2 => 
            array (
                'id' => '3',
                'key' => 'app_slogan',
                'name' => 'App Slogan',
                'value' => 'LaraClassified - Geo Classified Ads CMS',
            'description' => 'Website slogan (for Meta Title)',
                'field' => '',
                'parent_id' => '1',
                'lft' => '5',
                'rgt' => '6',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:27:49',
            ),
            3 => 
            array (
                'id' => '4',
                'key' => 'app_theme',
                'name' => 'Theme',
                'value' => '',
            'description' => 'Supported: blue, yellow, green, red (or empty)',
                'field' => '',
                'parent_id' => '1',
                'lft' => '7',
                'rgt' => '8',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 17:32:55',
            ),
            4 => 
            array (
                'id' => '5',
                'key' => 'app_email',
                'name' => 'Email',
                'value' => 'contact@larapen.com',
                'description' => 'The email address that all emails from the contact form will go to.',
                'field' => '{"name":"value","label":"Value","type":"email"}',
                'parent_id' => '1',
                'lft' => '9',
                'rgt' => '10',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:27:49',
            ),
            5 => 
            array (
                'id' => '6',
                'key' => 'app_phone_number',
                'name' => 'Phone number',
                'value' => NULL,
                'description' => 'Website phone number',
                'field' => '',
                'parent_id' => '1',
                'lft' => '11',
                'rgt' => '12',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:27:49',
            ),
            6 => 
            array (
                'id' => '7',
                'key' => 'activation_geolocation',
                'name' => 'Geolocation activation',
                'value' => '1',
                'description' => 'Geolocation activation',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '0',
                'lft' => '14',
                'rgt' => '19',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            7 => 
            array (
                'id' => '8',
                'key' => 'app_default_country',
                'name' => 'Default Country',
                'value' => 'CA',
            'description' => 'Default country (ISO alpha-2 codes - e.g. US)',
                'field' => '',
                'parent_id' => '7',
                'lft' => '15',
                'rgt' => '16',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:27:49',
            ),
            8 => 
            array (
                'id' => '9',
                'key' => 'activation_country_flag',
                'name' => 'Show country flag on top',
                'value' => '1',
                'description' => 'Show country flag on top page',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '7',
                'lft' => '17',
                'rgt' => '18',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:27:49',
            ),
            9 => 
            array (
                'id' => '10',
                'key' => 'activation_guests_can_post',
                'name' => 'Guests can post Ads',
                'value' => '1',
                'description' => 'Guest can post Ad',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '0',
                'lft' => '20',
                'rgt' => '25',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            10 => 
            array (
                'id' => '11',
                'key' => 'require_users_activation',
                'name' => 'Users activation required',
                'value' => '1',
                'description' => 'Users activation required',
                'field' => '{"name":"value","label":"Required","type":"checkbox"}',
                'parent_id' => '10',
                'lft' => '21',
                'rgt' => '22',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:27:49',
            ),
            11 => 
            array (
                'id' => '12',
                'key' => 'require_ads_activation',
                'name' => 'Ads activation required',
                'value' => '0',
                'description' => 'Ads activation required',
                'field' => '{"name":"value","label":"Required","type":"checkbox"}',
                'parent_id' => '10',
                'lft' => '23',
                'rgt' => '24',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:27:49',
            ),
            12 => 
            array (
                'id' => '13',
                'key' => 'activation_social_login',
                'name' => 'Social Login Activation',
                'value' => '0',
                'description' => 'Allow users to connect via social networks',
                'field' => '{"name":"value","label":"Required","type":"checkbox"}',
                'parent_id' => '0',
                'lft' => '38',
                'rgt' => '39',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            13 => 
            array (
                'id' => '14',
                'key' => 'activation_facebook_comments',
                'name' => 'Facebook Comments activation',
                'value' => '0',
                'description' => 'Allow Facebook comments on single page',
                'field' => '{"name":"value","label":"Required","type":"checkbox"}',
                'parent_id' => '0',
                'lft' => '36',
                'rgt' => '37',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            14 => 
            array (
                'id' => '15',
                'key' => 'show_powered_by',
                'name' => 'Show Powered by',
                'value' => '1',
                'description' => 'Show Powered by infos',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '0',
                'lft' => '26',
                'rgt' => '27',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            15 => 
            array (
                'id' => '16',
                'key' => 'google_site_verification',
                'name' => 'Google site verification content',
                'value' => NULL,
                'description' => 'Google site verification content',
                'field' => '',
                'parent_id' => '0',
                'lft' => '28',
                'rgt' => '31',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            16 => 
            array (
                'id' => '17',
                'key' => 'msvalidate',
                'name' => 'Bing site verification content',
                'value' => NULL,
                'description' => 'Bing site verification content',
                'field' => '',
                'parent_id' => '18',
                'lft' => '33',
                'rgt' => '34',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:28:49',
            ),
            17 => 
            array (
                'id' => '18',
                'key' => 'alexa_verify_id',
                'name' => 'Alexa site verification content',
                'value' => NULL,
                'description' => 'Alexa site verification content',
                'field' => '',
                'parent_id' => '18',
                'lft' => '35',
                'rgt' => '36',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 00:28:49',
            ),
            18 => 
            array (
                'id' => '19',
                'key' => 'activation_home_stats',
                'name' => 'Show Homepage Stats',
                'value' => '1',
            'description' => 'Show Homepage Stats (bottom page)',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '0',
                'lft' => '32',
                'rgt' => '33',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            19 => 
            array (
                'id' => '20',
                'key' => 'activation_serp_left_sidebar',
                'name' => 'Search left sidebar activation',
                'value' => '0',
            'description' => 'Search page (Left sidebar activation)',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '16',
                'lft' => '29',
                'rgt' => '30',
                'depth' => '2',
                'active' => '0',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            20 => 
            array (
                'id' => '21',
                'key' => 'seo_google_analytics',
                'name' => 'Google Analytics\'s tracking code',
                'value' => NULL,
                'description' => 'Google Analytics\'s tracking code',
                'field' => '{"name":"value","label":"Value","type":"textarea"}',
                'parent_id' => '0',
                'lft' => '34',
                'rgt' => '35',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            21 => 
            array (
                'id' => '22',
                'key' => 'facebook_page_url',
                'name' => 'Facebook - Page URL',
                'value' => 'https://web.facebook.com/larapencom',
                'description' => 'Website Facebook Page URL',
                'field' => '',
                'parent_id' => '0',
                'lft' => '40',
                'rgt' => '47',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            22 => 
            array (
                'id' => '23',
                'key' => 'facebook_page_id',
                'name' => 'Facebook - Page ID',
                'value' => '806182476160185',
            'description' => 'Website Facebook Page ID (Not username)',
                'field' => '',
                'parent_id' => '22',
                'lft' => '41',
                'rgt' => '42',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:26:15',
            ),
            23 => 
            array (
                'id' => '24',
                'key' => 'facebook_client_id',
                'name' => 'Facebook Client ID',
                'value' => NULL,
                'description' => 'Facebook Client ID',
                'field' => '',
                'parent_id' => '22',
                'lft' => '43',
                'rgt' => '44',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:26:15',
            ),
            24 => 
            array (
                'id' => '25',
                'key' => 'facebook_client_secret',
                'name' => 'Facebook Client Secret',
                'value' => NULL,
                'description' => 'Facebook Client Secret',
                'field' => '',
                'parent_id' => '22',
                'lft' => '45',
                'rgt' => '46',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:26:15',
            ),
            25 => 
            array (
                'id' => '26',
                'key' => 'google_client_id',
                'name' => 'Google Client ID',
                'value' => NULL,
                'description' => 'Google Client ID',
                'field' => '',
                'parent_id' => '0',
                'lft' => '48',
                'rgt' => '49',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            26 => 
            array (
                'id' => '27',
                'key' => 'google_client_secret',
                'name' => 'Google Client Secret',
                'value' => NULL,
                'description' => 'Google Client Secret',
                'field' => '',
                'parent_id' => '26',
                'lft' => '53',
                'rgt' => '54',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 01:42:29',
            ),
            27 => 
            array (
                'id' => '28',
                'key' => 'googlemaps_key',
                'name' => 'Google Maps key',
                'value' => 'AIzaSyD9KDb3Cu9qMX-0jyj6G0Ke4Yd-GBax4Xo',
                'description' => 'Google Maps key',
                'field' => '',
                'parent_id' => '26',
                'lft' => '55',
                'rgt' => '56',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 01:42:29',
            ),
            28 => 
            array (
                'id' => '29',
                'key' => 'twitter_url',
                'name' => 'Twitter - URL',
                'value' => 'https://twitter.com/larapencom',
                'description' => 'Website Twitter URL',
                'field' => '',
                'parent_id' => '0',
                'lft' => '50',
                'rgt' => '57',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            29 => 
            array (
                'id' => '30',
                'key' => 'twitter_username',
                'name' => 'Twitter - Username',
                'value' => 'larapencom',
                'description' => 'Website Twitter username',
                'field' => '',
                'parent_id' => '29',
                'lft' => '51',
                'rgt' => '52',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:29:26',
            ),
            30 => 
            array (
                'id' => '31',
                'key' => 'twitter_client_id',
                'name' => 'Twitter Client ID',
                'value' => NULL,
                'description' => 'Twitter Client ID',
                'field' => '',
                'parent_id' => '29',
                'lft' => '53',
                'rgt' => '54',
                'depth' => '2',
                'active' => '0',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:29:26',
            ),
            31 => 
            array (
                'id' => '32',
                'key' => 'twitter_client_secret',
                'name' => 'Twitter Client Secret',
                'value' => NULL,
                'description' => 'Twitter Client Secret',
                'field' => '',
                'parent_id' => '29',
                'lft' => '55',
                'rgt' => '56',
                'depth' => '2',
                'active' => '0',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:29:26',
            ),
            32 => 
            array (
                'id' => '33',
                'key' => 'activation_recaptcha',
                'name' => 'Recaptcha activation',
                'value' => '0',
                'description' => 'Recaptcha activation',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '0',
                'lft' => '58',
                'rgt' => '63',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            33 => 
            array (
                'id' => '34',
                'key' => 'recaptcha_public_key',
                'name' => 'reCAPTCHA public key',
                'value' => NULL,
                'description' => 'reCAPTCHA public key',
                'field' => '',
                'parent_id' => '33',
                'lft' => '59',
                'rgt' => '60',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:29:26',
            ),
            34 => 
            array (
                'id' => '35',
                'key' => 'recaptcha_private_key',
                'name' => 'reCAPTCHA private key',
                'value' => NULL,
                'description' => 'reCAPTCHA private key',
                'field' => '',
                'parent_id' => '33',
                'lft' => '61',
                'rgt' => '62',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:29:26',
            ),
            35 => 
            array (
                'id' => '36',
                'key' => 'paypal_mode',
                'name' => 'PayPal mode',
                'value' => 'sandbox',
            'description' => 'PayPal mode (e.g. sandbox, live)',
                'field' => '',
                'parent_id' => '0',
                'lft' => '88',
                'rgt' => '95',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            36 => 
            array (
                'id' => '37',
                'key' => 'paypal_username',
                'name' => 'PayPal username',
                'value' => NULL,
                'description' => 'PayPal username',
                'field' => '',
                'parent_id' => '36',
                'lft' => '89',
                'rgt' => '90',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:32:06',
            ),
            37 => 
            array (
                'id' => '38',
                'key' => 'paypal_password',
                'name' => 'PayPal password',
                'value' => NULL,
                'description' => 'PayPal password',
                'field' => '',
                'parent_id' => '36',
                'lft' => '91',
                'rgt' => '92',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:32:06',
            ),
            38 => 
            array (
                'id' => '39',
                'key' => 'paypal_signature',
                'name' => 'PayPal signature',
                'value' => NULL,
                'description' => 'PayPal signature',
                'field' => '',
                'parent_id' => '36',
                'lft' => '93',
                'rgt' => '94',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:32:06',
            ),
            39 => 
            array (
                'id' => '40',
                'key' => 'mail_driver',
                'name' => 'Mail driver',
                'value' => 'smtp',
                'description' => 'e.g. smtp, mail, sendmail, mailgun, mandrill, ses',
                'field' => '',
                'parent_id' => '0',
                'lft' => '64',
                'rgt' => '75',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            40 => 
            array (
                'id' => '41',
                'key' => 'mail_host',
                'name' => 'Mail host',
                'value' => NULL,
                'description' => 'SMTP host',
                'field' => '',
                'parent_id' => '40',
                'lft' => '65',
                'rgt' => '66',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:31:42',
            ),
            41 => 
            array (
                'id' => '42',
                'key' => 'mail_port',
                'name' => 'Mail port',
                'value' => '25',
            'description' => 'SMTP port (e.g. 25, 587, ...)',
                'field' => '',
                'parent_id' => '40',
                'lft' => '67',
                'rgt' => '68',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:31:42',
            ),
            42 => 
            array (
                'id' => '43',
                'key' => 'mail_encryption',
                'name' => 'Mail encryption',
                'value' => 'tls',
            'description' => 'SMTP encryption (e.g. tls, ssl, starttls)',
                'field' => '',
                'parent_id' => '40',
                'lft' => '69',
                'rgt' => '70',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:31:42',
            ),
            43 => 
            array (
                'id' => '44',
                'key' => 'mail_username',
                'name' => 'Mail username',
                'value' => NULL,
                'description' => 'SMTP username',
                'field' => '',
                'parent_id' => '40',
                'lft' => '71',
                'rgt' => '72',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:31:42',
            ),
            44 => 
            array (
                'id' => '45',
                'key' => 'mail_password',
                'name' => 'Mail password',
                'value' => NULL,
                'description' => 'SMTP password',
                'field' => '',
                'parent_id' => '40',
                'lft' => '73',
                'rgt' => '74',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:31:42',
            ),
            45 => 
            array (
                'id' => '46',
                'key' => 'mailgun_domain',
                'name' => 'Mailgun domain',
                'value' => NULL,
                'description' => 'Mailgun domain',
                'field' => '',
                'parent_id' => '0',
                'lft' => '76',
                'rgt' => '79',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            46 => 
            array (
                'id' => '47',
                'key' => 'mailgun_secret',
                'name' => 'Mailgun secret',
                'value' => NULL,
                'description' => 'Mailgun secret',
                'field' => '',
                'parent_id' => '46',
                'lft' => '77',
                'rgt' => '78',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:31:42',
            ),
            47 => 
            array (
                'id' => '48',
                'key' => 'mandrill_secret',
                'name' => 'Mandrill secret',
                'value' => NULL,
                'description' => 'Mandrill secret',
                'field' => '',
                'parent_id' => '0',
                'lft' => '80',
                'rgt' => '81',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            48 => 
            array (
                'id' => '49',
                'key' => 'ses_key',
                'name' => 'SES key',
                'value' => NULL,
                'description' => 'SES key',
                'field' => '',
                'parent_id' => '0',
                'lft' => '82',
                'rgt' => '87',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            49 => 
            array (
                'id' => '50',
                'key' => 'ses_secret',
                'name' => 'SES secret',
                'value' => NULL,
                'description' => 'SES secret',
                'field' => '',
                'parent_id' => '49',
                'lft' => '83',
                'rgt' => '84',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:32:06',
            ),
            50 => 
            array (
                'id' => '51',
                'key' => 'ses_region',
                'name' => 'SES region',
                'value' => NULL,
                'description' => 'SES region',
                'field' => '',
                'parent_id' => '49',
                'lft' => '85',
                'rgt' => '86',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:32:06',
            ),
            51 => 
            array (
                'id' => '52',
                'key' => 'stripe_secret',
                'name' => 'Stripe secret',
                'value' => NULL,
                'description' => 'Stripe secret',
                'field' => '',
                'parent_id' => '53',
                'lft' => '97',
                'rgt' => '98',
                'depth' => '2',
                'active' => '0',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:31:42',
            ),
            52 => 
            array (
                'id' => '53',
                'key' => 'stripe_key',
                'name' => 'Stripe key',
                'value' => NULL,
                'description' => 'Stripe key',
                'field' => '',
                'parent_id' => '0',
                'lft' => '96',
                'rgt' => '99',
                'depth' => '1',
                'active' => '0',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            53 => 
            array (
                'id' => '54',
                'key' => 'sparkpost_secret',
                'name' => 'Sparkpost secret',
                'value' => NULL,
                'description' => 'Sparkpost secret',
                'field' => '',
                'parent_id' => '0',
                'lft' => '100',
                'rgt' => '101',
                'depth' => '1',
                'active' => '0',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            54 => 
            array (
                'id' => '55',
                'key' => 'app_cache_expire',
                'name' => 'Cache Expire duration',
                'value' => '60',
            'description' => 'Cache Expire duration (in seconde)',
                'field' => '',
                'parent_id' => '0',
                'lft' => '102',
                'rgt' => '103',
                'depth' => '1',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 02:33:22',
            ),
            55 => 
            array (
                'id' => '56',
                'key' => 'app_cookie_expire',
                'name' => 'Cookie Expire duration',
                'value' => '2592000',
            'description' => 'Cookie Expire duration (in seconde)',
                'field' => '',
                'parent_id' => '55',
                'lft' => '111',
                'rgt' => '112',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 01:42:29',
            ),
            56 => 
            array (
                'id' => '57',
                'key' => 'activation_minify_html',
                'name' => 'HTML Minify activation',
                'value' => '0',
                'description' => 'Optimization - HTML Minify activation',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '55',
                'lft' => '113',
                'rgt' => '114',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 01:42:29',
            ),
            57 => 
            array (
                'id' => '58',
                'key' => 'activation_http_cache',
                'name' => 'HTTP Cache activation',
                'value' => '0',
                'description' => 'Optimization - HTTP Cache activation',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => '55',
                'lft' => '115',
                'rgt' => '116',
                'depth' => '2',
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 01:42:29',
            ),
            58 => 
            array (
                'id' => '59',
                'key' => 'show_country_svgmap',
                'name' => 'Show country SVG map',
                'value' => '1',
                'description' => 'Show country SVG map on the homepage',
                'field' => '{"name":"value","label":"Show","type":"checkbox"}',
                'parent_id' => '0',
                'lft' => '200',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => '60',
                'key' => 'ads_pictures_number',
                'name' => 'Ad\'s photos number',
                'value' => '3',
                'description' => 'Ad\'s photos number',
                'field' => '',
                'parent_id' => NULL,
                'lft' => '0',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 17:31:46',
            ),
            60 => 
            array (
                'id' => '61',
                'key' => 'show_ad_on_googlemap',
                'name' => 'Show Ads on Google Maps',
                'value' => '0',
            'description' => 'Show Ads on Google Maps (Single page only)',
                'field' => '{"name":"value","label":"Show","type":"checkbox"}',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => '62',
                'key' => 'custom_css',
                'name' => 'Custom CSS',
                'value' => NULL,
                'description' => 'Custom CSS for your site',
                'field' => '{"name":"value","label":"Value","type":"textarea"}',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-16 15:15:25',
            ),
            62 =>
            array (
                'id' => '63',
                'key' => 'ads_review_activation',
                'name' => 'Ads review activation',
                'value' => '0',
                'description' => 'Ads review activation',
                'field' => '{"name":"value","label":"Activation","type":"checkbox"}',
                'parent_id' => 10,
                'lft' => 23,
                'rgt' => 24,
                'depth' => 2,
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-14 23:27:49',
            ),
            63 =>
            array (
                'id' => '64',
                'key' => 'facebook_page_fans',
                'name' => 'Facebook - Page fans',
                'value' => NULL,
                'description' => 'Website Facebook Page number of fans',
                'field' => '',
                'parent_id' => 22,
                'lft' => 41,
                'rgt' => 42,
                'depth' => 2,
                'active' => '1',
                'created_at' => NULL,
                'updated_at' => '2016-06-15 01:26:15',
            ),
        ));
        
        
    }
}
